services:
  - type: web
    name: aurum-vault-api
    env: node
    plan: free
    rootDir: backend/core-api
    buildCommand: npm install --include=dev && npx prisma generate && npx prisma migrate resolve --applied 20260115224308_add_portal_status && tsc && npx prisma migrate deploy
    startCommand: npm run start:prod
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
